import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faHome } from '@fortawesome/free-solid-svg-icons';
import Link from "next/link";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="{inter.className}"  >
       
        <nav className="min-w-screen flex   flex-row items-center bg-gradient-to-r from-cyan-500 to-blue-500 overflow-hidden">
        <div className="flex flex-row ">
        <FontAwesomeIcon icon={faHome} className='h-15 w-16' />
          </div>
        
          {/* <a href="#">Tailwind</a> */}
          <div className="flex flex-row  basis-3/4">
            <ul className="flex flex-row w-full justify-around">
                <li><Link href="/Home">Home</Link></li>
                <li>Cards</li>
                <li>Footer</li>
                <li>NavBars</li>
                <li>Testimonials</li>
            </ul>
            </div>
            <div className=" flex basis-1/4 flex-row justify-around items-center">
              <button className="h-10 w-20 rounded-lg bg-yellow-600 hover:bg-green-400 hover:border-b-4 ">Login</button>
              <button className="h-10 w-20 rounded-lg bg-yellow-600 buttonstyle">Sign Up</button>
             
            </div>
          
        </nav>





        {children}</body>
    </html>
  );
}
